### ISSUE TITLE
Ideas & discussion for Issue #1

### ISSUE THREAD

**Issue by atuttle** [atuttle/PhoneGapTips#2]
Feel free to leave comments here with links to things you'd like to see in the first issue -- as well as anything else. At this stage, anything's fair game. Even if you want to write a short editorial. :)

It's also totally fine to discuss the things listed here; doesn't just have to be a dump of source material.

**Comment by atuttle** [comment]
http://lemonjar.com/iosconsole/ - As of iOS 8 the trusty old **iPhone Configuration Utility** (useful for viewing the device logs) no longer works. Apple has decided that you should use XCode to view device logs instead. If you've started your project recently enough to be using the PhoneGap/Cordova CLI and occasionally building in XCode, this may not be a problem. But if you've got a legacy project created before the advent of the CLIs and built using a cloud service like PhoneGap:Build, (and not enough time to convert it to a CLI-based app) console access in XCode is not quite so easy. **iOS Console** puts that console back at your fingertips: just plug your device in over USB and open the app.

**Comment by atuttle** [comment]
[PhoneGap Day](http://pgday.phonegap.com/archive/) (US) 2016 will be held January 28-29 in Utah. [Call for speakers](https://docs.google.com/forms/d/1T7dEnZ44bXC9zRtzyg0VMO9WTNlwSUtu-PgDGA2pTDg/viewform) is open, and anyone interested in sponsoring can email [jgray@adobe.com](mailto:jgray@adobe.com). More details will be announced soon! (The skiing in Utah in late January is supposed to be really nice!)

**Comment by atuttle** [comment]
Using Ionic to build your PhoneGap app? There's a really good chance you can improve your app's performance with tips in this [Ultimate AngularJS and Ionic performance cheat sheet](http://julienrenaux.fr/2015/08/24/ultimate-angularjs-and-ionic-performance-cheat-sheet/).

**Comment by atuttle** [comment]
https://www.ingeniumweb.com/blog/post/ionic-vs-f7-vs-famous-vs-onsenui-taking-a-walk-through-the-key-differences/2401/

**Comment by cfjedimaster** [comment]
Suggesting my own link because I can: http://www.raymondcamden.com/2015/09/18/integrating-the-calendar-into-your-ionic-app

**Comment by atuttle** [comment]
https://medium.com/@dlpasco/apple-tv-a-world-without-webkit-5c428a64a6dd

**Comment by atuttle** [comment]
http://slack.cordova.io/

**Comment by atuttle** [comment]
"From the archives"

http://coenraets.org/blog/2013/05/top-10-performance-techniques-for-phonegap-applications/

**Comment by atuttle** [comment]
http://devgirl.org/2015/09/22/sample-phonegap-app-with-reactjs/

**Comment by cfjedimaster** [comment]
Tools for Apache Cordova (TACO) - http://taco.tools/index.html. An interesting set of utilities that could make working with Cordova easier.

**Comment by atuttle** [comment]
Scheduled for 10/5 at 7-something am US-Eastern.
